import os
import yaml
import shutil
def recursive_key_value_assign(d,ks,v):
    """
    Recursive value assignment to a nested dict

    Arguments:
        d {dict} -- dict
        ks {list} -- list of hierarchical keys
        v {value} -- value to assign
    """
    
    if len(ks) > 1:
        recursive_key_value_assign(d[ks[0]],ks[1:],v)
    elif len(ks) == 1:
        d[ks[0]] = v
 
def load_config(config_path):
    """
    Loads yaml config file and overwrites parameters with function arguments and --arg_config parameters

    Arguments:
        checkpoint_dir {str} -- Checkpoint directory where config file was copied to

    Keyword Arguments:
        batch_size {int} -- [description] (default: {None})
        max_epoch {int} -- "epochs" (number of scenes) to train (default: {None})
        data_path {str} -- path to scenes with contact grasp data (default: {None})
        arg_configs {list} -- Overwrite config parameters by hierarchical command line arguments (default: {[]})
        save {bool} -- Save overwritten config file (default: {False})

    Returns:
        [dict] -- Config
    """
    print(config_path)
    
    with open(config_path,'r') as f:
        global_config = yaml.safe_load(f)
    return global_config

def load_config_inference(checkpoint_dir,config_file=None, batch_size=None, max_epoch=None, data_path=None, arg_configs=[], save=False):
    """
    Loads yaml config file and overwrites parameters with function arguments and --arg_config parameters

    Arguments:
        checkpoint_dir {str} -- Checkpoint directory where config file was copied to

    Keyword Arguments:
        batch_size {int} -- [description] (default: {None})
        max_epoch {int} -- "epochs" (number of scenes) to train (default: {None})
        data_path {str} -- path to scenes with contact grasp data (default: {None})
        arg_configs {list} -- Overwrite config parameters by hierarchical command line arguments (default: {[]})
        save {bool} -- Save overwritten config file (default: {False})

    Returns:
        [dict] -- Config
    """
    config_file = config_file if config_file is not None else 'transformer_config.yaml'
    config_path = os.path.join(checkpoint_dir, config_file)
    config_path = config_path if os.path.exists(config_path) else os.path.join(os.path.dirname(__file__),config_file)
    with open(config_path,'r') as f:
        global_config = yaml.safe_load(f)

    for conf in arg_configs:
        k_str, v = conf.split(':')
        try:
            v = eval(v)
        except:
            pass
        ks = [int(k) if k.isdigit() else k for k in k_str.split('.')]
        
        recursive_key_value_assign(global_config, ks, v)
        
    if batch_size is not None:
        global_config['OPTIMIZER']['batch_size'] = int(batch_size)
    if max_epoch is not None:
        global_config['OPTIMIZER']['max_epoch'] = int(max_epoch)
    if data_path is not None:
        global_config['DATA']['data_path'] = data_path
        
    global_config['DATA']['classes'] = None
    
    if save:
        with open(os.path.join(checkpoint_dir, 'transformer_config.yaml'),'w') as f:
            yaml.dump(global_config, f)

    return global_config


PYTHON_WARNING = "\n\n'''\n\n-----------------DO NOT EDIT THIS FILE-----------------\n\n'''\n\n"
YAML_WARNING = "\n\n\n\n# -----------------DO NOT EDIT THIS FILE--------------------\n\n\n\n"

def add_warning(file_path):
    """
    Inserts a comment warning at the beginning of a .py or .yaml file.
    
    :param file_path: Path to the file where the warning should be added.
    """
    if file_path.endswith('.py'):
        warning = PYTHON_WARNING
    elif file_path.endswith('.yaml') or file_path.endswith('.yml'):
        warning = YAML_WARNING
    else:
        return  # Do nothing for other file types

    with open(file_path, 'r+', encoding='utf-8') as f:
        content = f.read()
        if not content.startswith(warning.strip()):  # Avoid duplicate warnings
            f.seek(0)
            f.write(warning + content)

def copy_file_if_not_exists(source_file, target_directory):
    """
    Copies a file into a target directory only if a file with the same name does not already exist.
    If the file exists, prints a message and does nothing.

    :param source_file: Path to the source file.
    :param target_directory: Directory where the file should be copied.
    :return: Path of the copied file if copied, or None if the file already exists.
    """
    # Convert to absolute paths
    source_file = os.path.abspath(source_file)
    target_directory = os.path.abspath(target_directory)

    # Ensure target directory exists
    if not os.path.isdir(target_directory):
        os.makedirs(target_directory, exist_ok=True)

    target_path = os.path.join(target_directory, os.path.basename(source_file))

    
    # Check if the file already exists (absolute path)
    if os.path.isfile(target_path):
        print(f"File already exists: {target_path}. Skipping copy.")
        return None

    # Perform the copy operation
    shutil.copy2(source_file, target_path)
    add_warning(target_path)
    # Double-check existence after copy
    if os.path.isfile(target_path):
        print(f"File successfully copied to: {target_path}")
        return target_path
    else:
        print(f"Error: Copy operation completed but file not found at {target_path}")
        return None

def force_copy_file(source_file, target_directory):
    """
    Copies a file into a target directory, overwriting the existing file if it already exists.

    :param source_file: Path to the source file.
    :param target_directory: Directory where the file should be copied.
    :return: Path of the copied file.
    """
    if not os.path.exists(target_directory):
        os.makedirs(target_directory)  # Ensure the target directory exists

    target_path = os.path.join(target_directory, os.path.basename(source_file))

    shutil.copy2(source_file, target_path)
    add_warning(target_path)
    print(f"Force copied (overwritten if existed) to: {target_path} with a warning added.")
    return target_path